const CREATED = 201;
const ERROR_CODE = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;
const MONGO_DUPLICATE_KEY_ERROR = 11000;

module.exports = {
  CREATED,
  ERROR_CODE,
  UNAUTHORIZED,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  MONGO_DUPLICATE_KEY_ERROR,
  CONFLICT_ERROR,
};
